services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ticket_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/ticket_db?schema=public"
      JWT_SECRET: "h1wHcIr8vxltVcyMGjtPWrfgjkZgBTSirhyNJwPcUFOQ6PZtw9Cn2vRye+DB9SF4"
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "8080:80"
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
